In [1]:
import numpy as np
import pandas as pd


# -----------------------------
# Utility Functions
# -----------------------------

def load_data(file_path: str) -> np.ndarray:
    """Load CSV and convert to NumPy array"""
    try:
        df = pd.read_csv(file_path)
        print("✅ Data loaded successfully")
        print("\n📊 Raw Data:\n", df.head())
        return df.values
    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None


def create_random_matrices(shape=(3, 3)):
    """Generate two random matrices"""
    np.random.seed(0)
    A = np.random.randint(1, 10, size=shape)
    B = np.random.randint(1, 10, size=shape)

    print("\n🔢 Matrix A:\n", A)
    print("Shape:", A.shape)

    print("\n🔢 Matrix B:\n", B)
    print("Shape:", B.shape)

    return A, B


def elementwise_multiplication(A, B):
    """Perform element-wise multiplication"""
    result = A * B
    print("\n✖️ Element-wise Multiplication:\n", result)
    return result


def matrix_multiplication(A, B):
    """Perform matrix multiplication"""
    result = np.dot(A, B)
    print("\n🔗 Matrix Multiplication:\n", result)
    return result


def determinant_and_inverse(A):
    """Compute determinant and inverse"""
    det = np.linalg.det(A)
    print("\n📐 Determinant of A:", det)

    if det != 0:
        inv = np.linalg.inv(A)
        print("\n🔄 Inverse of A:\n", inv)
    else:
        print("❌ Matrix not invertible")
        inv = None

    return det, inv


def normalize_array(arr):
    """Normalize 1D array to range [0,1]"""
    norm = (arr - arr.min()) / (arr.max() - arr.min())

    print("\n📏 Original Array:", arr)
    print("📊 Normalized Array:", norm)

    return norm


def broadcasting_example(data):
    """Subtract column mean using broadcasting"""
    col_mean = data.mean(axis=0)
    result = data - col_mean

    print("\n📊 Original Data:\n", data)
    print("\n📉 Column Means:", col_mean)
    print("\n⚡ After Broadcasting:\n", result)

    return result


# -----------------------------
# Main Pipeline
# -----------------------------

def main():
    FILE_PATH = "numpy_data.csv"

    # Step 1: Load data
    data = load_data(FILE_PATH)
    if data is None:
        return

    # Step 2: Create matrices
    A, B = create_random_matrices()

    # Step 3: Element-wise multiplication
    _ = elementwise_multiplication(A, B)

    # Step 4: Matrix multiplication
    _ = matrix_multiplication(A, B)

    # Step 5: Determinant & inverse
    _ = determinant_and_inverse(A)

    # Step 6: Normalize 1D array
    arr = np.array([10, 20, 30, 40, 50])
    _ = normalize_array(arr)

    # Step 7: Broadcasting example
    _ = broadcasting_example(data)


# -----------------------------
# Run Script
# -----------------------------

if __name__ == "__main__":
    main()

✅ Data loaded successfully

📊 Raw Data:
    col_1  col_2  col_3  col_4  col_5
0     52     93     15     72     61
1     21     83     87     75     75
2     88     24      3     22     53
3      2     88     30     38      2
4     64     60     21     33     76

🔢 Matrix A:
 [[6 1 4]
 [4 8 4]
 [6 3 5]]
Shape: (3, 3)

🔢 Matrix B:
 [[8 7 9]
 [9 2 7]
 [8 8 9]]
Shape: (3, 3)

✖️ Element-wise Multiplication:
 [[48  7 36]
 [36 16 28]
 [48 24 45]]

🔗 Matrix Multiplication:
 [[ 89  76  97]
 [136  76 128]
 [115  88 120]]

📐 Determinant of A: 27.999999999999986

🔄 Inverse of A:
 [[ 1.          0.25       -1.        ]
 [ 0.14285714  0.21428571 -0.28571429]
 [-1.28571429 -0.42857143  1.57142857]]

📏 Original Array: [10 20 30 40 50]
📊 Normalized Array: [0.   0.25 0.5  0.75 1.  ]

📊 Original Data:
 [[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]

📉 Column Means: [45.4 69.6 31.2 48.  53.4]

⚡ After Broadcasting:
 [[  6.6  23.4 -16.2  24.    7.6]
 [-24.4  13